### ISSUE TITLE
Pitch up moment sometimes

### ISSUE THREAD

**Issue by Zaretto** [5H1N0B11/flightgear-mirage2000#79]

**Comment by Octal450** [comment]
I'm looking at this, its due to the G control being "surprised" by the sudden change in actual G due to rolling with the high roll rate of this plane. I think I can fix it by leading the G in the proper direction.

**Comment by paccalin** [comment]
If you are talking of the pitch up tendancy when leveling after a turn, this is most certainly due to the lag filter applied to the pilot pitch command.

The filter output won't be at 0 just after the turn, even if the stick is neutral (and the tighter the turn the higher the filter output will be).

**Comment by Zaretto** [comment]
This is probably no longer valid since @paccalin rewrote the FCS.

**Comment by Octal450** [comment]
Fwiw, this was due to that I forgot to implement roll-pitch coupling logic to the load factor computation. Apparently, I never fixed it.

Kind Regards,
Josh
